from SimComponents import QueueType
from StandardSimComponents import test_one_of_each_generator_one_switch

test_one_of_each_generator_one_switch(QueueType.FIFO)
# test_one_of_each_generator_one_switch(QueueType.LIFO)
# test_one_of_each_generator_one_switch(QueueType.RANDO)

